language: java
services:
- docker
script:
- cd sdk
- docker build -t lusid-sdk-java-test .
- docker run -e FBN_TOKEN_URL=$FBN_TOKEN_URL -e FBN_USERNAME=$FBN_USERNAME -e FBN_PASSWORD=$FBN_PASSWORD
  -e FBN_CLIENT_ID=$FBN_CLIENT_ID -e FBN_CLIENT_SECRET=$FBN_CLIENT_SECRET -e FBN_LUSID_API_URL=$FBN_LUSID_API_URL -e FBN_SCOPE=$FBN_SCOPE
  -v $(pwd):/usr/src/ lusid-sdk-java-test
notifications:
  slack:
    rooms:
      secure: dtdpx/VDxKS5dL7BRdNN4l0QIUVpSXcaOR6n3eCi+cdGlcGjKpewywoWi1V/lKJyJ77p8lCec0jjgfRS5OgMPbtXJHaLQQbqZwZ9wUGeUwSvHJYbbrGzStW/ss+HpwNW8O0hbleFg3fD8BSPl4W9nOfpVqnv6KAl+mWaW0g4/d3DnxiZ2BtxF8dx+CgpXBDdebh7dYyKN41iTn13tBhsH0bo3sF8H5mfMtIhSqza9uc7yBLH70IdTcpHZkBoggMKE1DG2s3U+CYTMgV5WceSrSpkFo/xdbiAxfZ2Zv27CPWDL1rBQvXBFm+QYB08b/L7e/2uGn3G5UvJmLeTy0LXrA+cIXpmMEyHljmGZxaiUJqdZAjhbGJvevcPzoZ2rh2UATAuVQ1njECFLi/JQaAcpKlaHA4dvLSYZyp0JoLXufy9KMQ5PqGhrCmxcQWdo72HKnPQbal23nex5QVXncqtGo59Mb/QFsKnZOvsKpix0+arSD1MeRTJ1ik/hHGHFWx71mh0Ceya/HCp29LTc/f9KafUGfwUK9cfKmDo/PttNILDz2qxtbc/SlfnxRH3ZEMFbTphiZB3VzM0yu1Ys2g5y3HROFOmoPprvKcyCrax8l2qtTH/NAlETkQ0zLYp3yf9HBgUL+ZXsWYE9P7/pAshBGZ4gfZzVHukwy9O0Ps7kAE=
    on_failure: always
env:
  matrix:
    secure: luygIeyEiE2l8weoehktT9dqz9TUiELvQ1vZJKtV+IupJNCRolcoKye/WTt543zYAJm6/pduHx6XqP3h89wVHHcB4ThQpHt3um+3MqvX/kWjF93a+7s8MqL+msGbzwUr68J8/r6k4+I/LxDealOhaAUjVSEDBMBL/UuGnd/kOgrTIwvf8RK9UIMD90DZtdS+2Opfu5Y9QzmR3FcoyJAcdCP2Z9LtFZM1JiPg/qF4SCJ66XYbR5jpjD31B9jQANcWJyHq/uTb7sjVjK9j5Zp6QmEUukmeao6RCftlHhbjoLs0AJp862CccMiN9xxd/6Wk0G3vIy0jVSAPptWQg3SlqwCBgxahJ1guP7ZH1snpZBz1Yf7Gj8gI85IFDiMq5MgXfVrRPQ/qvyytSnWB/93lGzwg8HzFbpd9axeiAcUVm8O5KsIDauQlkHKSYQiC/UQu1vc5LkmkU1tTr/wqegST5/chWiANOJ3AoZJhNOOHYOOZJpQ0uGsY5u33k2ZO0q+kNaL0PxB14k6x+k96gtavBMt1r+xO0lSWHSLsOiviWjlv/mMZ5l6cjK1xBhXKWVmgb9POWcBfUXclX1MTHI3N4l4MRLFa+4OlcZ1adLHN7i/USgbjQf4OLrCr5g0g65H5U+d5r1SlrgGOXTLX2mSPKkff8fntmQADztNMvNsno1k=
